# This Makefile is deprecated.
# Please use the top-level Makefile in the root of the repository.
#
# To run pipeline commands, use the `pipeline-*` targets from the root Makefile.
# For example:
#   - `make pipeline-run`
#   - `make pipeline-lint`
#   - `make pipeline-smoke`
#
# For a full list of commands, run `make help` from the root of the repository.

.PHONY: all
all:
	@echo "This Makefile is deprecated. Please use the top-level Makefile."
