# Local execution profile for Snakemake
# To use: snakemake --profile config/profiles/local

# --- Cluster settings (not used for local) ---
cluster: "echo 'This is a local profile.'"

# --- Core settings ---
cores: 8
local-cores: 8
jobs: 4
max-jobs-per-second: 1
max-status-checks-per-second: 1
latency-wait: 60
use-conda: True

# --- Apptainer/Singularity settings ---
use-apptainer: True
apptainer-args: "--bind /data,/tmp"
apptainer-image: "docker://rnaseq-mini:latest"
